version: "3"
services:
  # Open source Headless CMS with customizable APIs
  strapi_cms:
    image: denisnv/wysiblocks_strapi_cms:latest
    build:
      context: ./strapi_cms/
      dockerfile: production.Dockerfile
