// Site
export const SET_CURRENT_PATH = "SET_CURRENT_PATH";
export const SET_LOCKED_PAGE_ID = "SET_LOCKED_PAGE_ID";
export const SET_SITE_DATA = "SET_SITE_DATA";
export const SET_SITE_EDIT_MODE = "SET_SITE_EDIT_MODE";
export const SET_BLOCKS_DATA = "SET_BLOCKS_DATA";
export const UPDATE_BLOCKS_DATA = "UPDATE_BLOCKS_DATA";
export const UPDATE_SITE_BLOCK_DATA = "UPDATE_SITE_BLOCK_DATA";
export const RESET_BLOCKS_DATA = "RESET_BLOCKS_DATA";
export const RESET_BLOCKS_TO_DELETE = "RESET_BLOCKS_TO_DELETE";
export const UPDATE_PAGES_DATA = "UPDATE_PAGES_DATA";
export const UPDATE_NAV_DATA = "UPDATE_NAV_DATA";
export const SET_CONTENT_BLOCK_TYPES_DATA = "SET_CONTENT_BLOCK_TYPES_DATA";
export const SET_SITE_BLOCK_TYPES_DATA = "SET_SITE_BLOCK_TYPES_DATA";
export const SET_NAV_WARNING = "SET_NAV_WARNING";
export const SET_FONT_STATUS = "SET_FONT_STATUS";

// UI
export const SET_HEADER_HEIGHT = "SET_HEADER_HEIGHT";
export const TOGGLE_DATA_SAVING_UI = "TOGGLE_DATA_SAVING_UI";

// Theme
export const UPDATE_THEME = "UPDATE_THEME";

// User
export const SET_USER = "SET_USER";
export const SET_ADMIN_RIGHTS = "SET_ADMIN_RIGHTS";
export const SET_CALLS_APPLICATIONS_STATE = "SET_CALLS_APPLICATIONS_STATE";
export const SET_SHOPPING_CALLS_APPLICATIONS_STATE =
  "SET_SHOPPING_CALLS_APPLICATIONS_STATE";
